In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import plotly.plotly as py
import numpy as np
import random
import time
import tables as tb
import tstables as tstb
import datetime
import plotly.plotly as py
import cufflinks as cf

In [2]:
ft = pd.read_excel("futures_table.xlsx")
ft.dropna().head()

,Commodity,Exchange,Exchange Symbol,Tick,Tick Value,Contract Size,MONTHS,Electronic Market Times (Chicago Time)
1,E-Mini S&P 500,CME/CME,ES,0.25,$12.50,$50 x Index,"H, M, U, Z",5:00pm - 4:00pm*
2,E-Mini Nasdaq,CME/CME,NQ,0.25,$5,$20 x Index,"H, M, U, Z",5:00pm - 4:00pm*
3,E-Mini Dow Jones - $5,CME/CBOT,YM,1,$5,$5 x Index,"H, M, U, Z",5:00pm - 4:00pm*
4,Mini Russell,ICE,TF,0.1,$5.00,$50 x Index,"H, M, U, Z",7:00 pm - 5:00pm
5,E-Mini Midcap 400,CME/CME,EMD,0.1,$10.00,$100 x Index,"H, M, U, Z",5:00pm - 4:00pm*

In [3]:
ft[ft['Exchange'] == 'ICE']

,Commodity,Exchange,Exchange Symbol,Tick,Tick Value,Contract Size,MONTHS,Electronic Market Times (Chicago Time)
4,Mini Russell,ICE,TF,0.1,$5.00,$50 x Index,"H, M, U, Z",7:00 pm - 5:00pm
34,US Dollar Index,ICE,DX,0.005,$5.00,1000 x Index,"H, M, U, Z",7:00pm - 4:00pm
38,Mini Gold,ICE,YG,0.1,$3.32,33.2 oz,"G, J, M, Q, V, Z",7:00pm - 5:00pm
41,Mini Silver,ICE,YI,0.001,$1.00,1000 oz,"F, H, K, N, U, Z",7:00pm - 5:00pm
53,Cotton,ICE,CT,0.01,$5.00,"50,000 lbs","H, K, N, U, Z",8:00pm - 1:20pm
54,Cocoa,ICE,CC,1,$10.00,10 tons,"H, K, N, U, Z",3:45am - 12:30pm
55,Sugar #11,ICE,SB,0.01,$11.20,"112,000 lbs","H, K, N, U, Z",2:30am - 12:00pm
56,Coffee,ICE,KC,0.05,$18.75,"37,500 lbs","H, K, N, U, Z",3:15am - 12:30pm

In [4]:
ft[ft['Tick'] == 0.1]

,Commodity,Exchange,Exchange Symbol,Tick,Tick Value,Contract Size,MONTHS,Electronic Market Times (Chicago Time)
4,Mini Russell,ICE,TF,0.1,$5.00,$50 x Index,"H, M, U, Z",7:00 pm - 5:00pm
5,E-Mini Midcap 400,CME/CME,EMD,0.1,$10.00,$100 x Index,"H, M, U, Z",5:00pm - 4:00pm*
36,Gold,CME/ COMEX,GC,0.1,$10.00,100 oz,"G, J, M, Q, V, Z",5:00pm - 4:00pm
37,E-Micro Gold,CME/ COMEX,MGC,0.1,$1.00,10 oz,"G, J, M, Q, V, Z",5:00pm - 4:00pm
38,Mini Gold,ICE,YG,0.1,$3.32,33.2 oz,"G, J, M, Q, V, Z",7:00pm - 5:00pm

In [5]:
ft = ft.set_index('Commodity')

In [6]:
ft.loc['10 Year Note']

Exchange                                        CME/ CBOT
Exchange Symbol                                        ZN
Tick                                          1/2 of 1/32
Tick Value                                         $15.63
Contract Size                                 $100,000.00
MONTHS                                         H, M, U, Z
Electronic Market Times (Chicago Time)    5:00pm - 4:00pm
Name: 10 Year Note, dtype: object

In [7]:
ft.loc['Coffee']

Exchange                                               ICE
Exchange Symbol                                         KC
Tick                                                  0.05
Tick Value                                          $18.75
Contract Size                                   37,500 lbs
MONTHS                                       H, K, N, U, Z
Electronic Market Times (Chicago Time)    3:15am - 12:30pm
Name: Coffee, dtype: object

In [8]:
ft.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63 entries, Indexes to E-Mini Natural Gas
Data columns (total 7 columns):
Exchange                                  53 non-null object
Exchange Symbol                           53 non-null object
Tick                                      53 non-null object
Tick Value                                53 non-null object
Contract Size                             53 non-null object
MONTHS                                    53 non-null object
Electronic Market Times (Chicago Time)    54 non-null object
dtypes: object(7)
memory usage: 6.4+ KB

In [10]:
ft.iplot(kind='bar', filename='fin_time_series_9', world_readable=True)  #.std, .mean, .sum, .cumsum can be used